using System.Globalization;
using System.Windows;

namespace CVmania.App.Localization;

/// <summary>
/// Tiny string table. Strings are pushed into <see cref="Application.Resources"/> so XAML can use
/// <c>{DynamicResource Key}</c> and switch language live; code uses <see cref="T"/> / <see cref="F"/>.
/// </summary>
public static class Loc
{
    public static readonly IReadOnlyList<(string Code, string Name)> Languages = new[] { ("en", "English"), ("ko", "한국어") };

    public static string Language { get; private set; } = "en";
    public static event Action? LanguageChanged;

    public static string DefaultLanguage()
    {
        var two = CultureInfo.CurrentUICulture.TwoLetterISOLanguageName;
        return Languages.Any(l => l.Code == two) ? two : "en";
    }

    public static void Apply(string lang)
    {
        if (!Languages.Any(l => l.Code == lang)) lang = "en";
        Language = lang;
        var res = Application.Current.Resources;
        foreach (var key in En.Keys)
        {
            res[key] = T(key);
        }
        LanguageChanged?.Invoke();
    }

    public static string T(string key)
    {
        if (Language == "ko" && Ko.TryGetValue(key, out var ko)) return ko;
        return En.TryGetValue(key, out var en) ? en : key;
    }

    public static string F(string key, params object?[] args) => string.Format(CultureInfo.InvariantCulture, T(key), args);

    /// <summary>Rows for the shortcuts window: (keys, what it does).</summary>
    public static IReadOnlyList<(string Keys, string Action)> ShortcutRows() => Language == "ko"
        ? new[]
        {
            ("Space", "재생 / 일시정지"),
            ("Esc", "정지 (팝업이 열려 있으면 닫기)"),
            ("← / →", "한 박자 이동 · Shift: 한 마디 · Ctrl: 10 ms"),
            ("Home / End", "곡 처음 / 끝으로"),
            ("드래그", "구간 선택 (스냅 격자에 맞춤)"),
            ("우클릭", "확정하지 않은 선택 지우기"),
            ("I / O", "선택 시작 / 끝 = 현재 재생 위치"),
            ("Enter", "선택을 구간으로 추가 · 구간 안이면 분할"),
            ("Delete", "구간 안 선택 부분 삭제 · 또는 선택한 구간 삭제"),
            ("L", "선택 구간 반복 재생"),
            ("P", "잘린 결과 미리듣기 ↔ 원곡"),
            ("Z", "전체 보기"),
            ("휠 / Ctrl+휠", "시간 확대·축소"),
            ("Shift+휠", "가로 스크롤"),
            ("Alt+휠", "파형 세로 배율"),
            ("가운데 드래그", "화면 이동"),
            ("구간 클릭", "구간 선택 (양 끝에 페이드 핸들 표시)"),
            ("Ctrl+O / F5 / Ctrl+E", ".osu 열기 / 다시 불러오기 / 내보내기"),
        }
        : new[]
        {
            ("Space", "Play / pause"),
            ("Esc", "Stop (closes an open popup first)"),
            ("← / →", "Move one beat · Shift: one measure · Ctrl: 10 ms"),
            ("Home / End", "Go to the start / end"),
            ("Drag", "Select a range (snapped to the grid)"),
            ("Right click", "Clear the unconfirmed selection"),
            ("I / O", "Selection start / end = current playhead"),
            ("Enter", "Keep the selection as a region · inside a region: split it"),
            ("Delete", "Remove the selected part of a region · or the selected region"),
            ("L", "Loop the selection"),
            ("P", "Preview the cut ↔ original"),
            ("Z", "Zoom to fit"),
            ("Wheel / Ctrl+wheel", "Zoom in time"),
            ("Shift+wheel", "Scroll"),
            ("Alt+wheel", "Waveform height"),
            ("Middle drag", "Pan"),
            ("Click a region", "Select it (fade handles appear at its ends)"),
            ("Ctrl+O / F5 / Ctrl+E", "Open .osu / reload / export"),
        };

    private static readonly Dictionary<string, string> En = new()
    {
        ["App.Title"] = "CV!mania by Tamania",
        ["Menu.File"] = "_File",
        ["Menu.Open"] = "_Open .osu...",
        ["Menu.Reload"] = "_Reload beatmap",
        ["Menu.Export"] = "_Export cut version...",
        ["Menu.Exit"] = "E_xit",
        ["Menu.View"] = "_View",
        ["Menu.ZoomFit"] = "Zoom to fit",
        ["Menu.FollowPlayhead"] = "Follow playhead while playing",
        ["Menu.FollowOsu"] = "Follow the beatmap selected in osu!",
        ["Menu.ShowNotes"] = "Show notes under the waveform",
        ["Menu.ShowBookmarks"] = "Show bookmarks",
        ["Menu.Language"] = "_Language",
        ["Menu.Help"] = "_Help",
        ["Menu.Shortcuts"] = "Keyboard shortcuts",
        ["Menu.About"] = "About CV!mania",
        ["Status.NotRunning"] = "osu! not running",
        ["Status.Reading"] = "osu! found - reading memory...",
        ["Status.Connected"] = "osu! {0} - {1}",
        ["Map.None"] = "No beatmap loaded - select a map in osu! or drop a .osu file here",
        ["Map.Info"] = "{0} · {1} · {2} objects · {3} red line(s) · main BPM {4} · {5}",
        ["Map.Follow"] = "Follow osu! selection",
        ["Map.Open"] = "Open .osu...",
        ["Map.Reload"] = "Reload",
        ["Bpm.Label"] = "BPM sections:",
        ["Snap.Label"] = "Snap:",
        ["Snap.Measure"] = "Measure",
        ["Snap.Off"] = "Off",
        ["Snap.Tip"] = "Selections snap to this grid. Lines are coloured like the osu! editor.",
        ["Transport.Play"] = "Play (Space)",
        ["Transport.Pause"] = "Pause (Space)",
        ["Transport.Stop"] = "Stop (Esc)",
        ["Transport.SelStart"] = "Selection start = playhead (I)",
        ["Transport.SelEnd"] = "Selection end = playhead (O)",
        ["Transport.Loop"] = "Loop selection (L)",
        ["Transport.Follow"] = "Follow playhead",
        ["Transport.ZoomFit"] = "Zoom to fit (Z)",
        ["Transport.Volume"] = "Volume",
        ["Transport.Preview"] = "PREVIEW: playing the cut result (P to return)",
        ["Regions.Title"] = "Regions to keep",
        ["Regions.Col.Start"] = "Start",
        ["Regions.Col.End"] = "End",
        ["Regions.Col.Length"] = "Length",
        ["Regions.Col.Out"] = "Output start",
        ["Regions.Col.FadeIn"] = "Start edge",
        ["Regions.Col.FadeOut"] = "End edge",
        ["Regions.Col.Grid"] = "Grid",
        ["Regions.Add"] = "Add / split selection (Enter)",
        ["Regions.Delete"] = "Delete selection or region (Del)",
        ["Regions.Clear"] = "Clear all regions",
        ["Regions.FadeIn"] = "Start edge...",
        ["Regions.FadeOut"] = "End edge...",
        ["Regions.None"] = "No regions yet (everything outside is cut).",
        ["Regions.Summary"] = "{0} region(s) → {1}",
        ["Selection.Text"] = "Selection {0} - {1} ({2})",
        ["Selection.Inside"] = "inside region {0}: Enter = split, Delete = remove this part",
        ["Selection.Outside"] = "Enter = keep as a region, right click = clear",
        ["Selection.StartOnly"] = "Selection start {0} - press O to set the end",
        ["Grid.Downbeat"] = "downbeat",
        ["Grid.OnBeat"] = "on beat",
        ["Grid.Off"] = "{0} ms off beat",
        ["Bottom.Preview"] = "Preview cut (P)",
        ["Bottom.BackToOriginal"] = "Back to original (P)",
        ["Bottom.Export"] = "Export...",
        ["Msg.AddRegionHint"] = "Add at least one region to preview or export.",
        ["Msg.Loaded"] = "Loaded {0} ({1} Hz, {2} ch, {3}). Drag on the waveform to select, Enter to keep it.",
        ["Msg.Decoding"] = "Decoding audio with BASS...",
        ["Msg.ReadFail"] = "Could not read {0}: {1}",
        ["Msg.AudioMissing"] = "Audio file '{0}' was not found next to the beatmap.",
        ["Msg.DecodeFail"] = "Could not decode audio: {0}",
        ["Msg.PlayFail"] = "Playback could not be started: {0}",
        ["Msg.Rendering"] = "Rendering preview...",
        ["Msg.PreviewReady"] = "Preview ready: {0} of audio. Click inside a region to seek, P to go back.",
        ["Msg.PreviewFail"] = "Preview failed: {0}",
        ["Msg.ReloadFail"] = "Could not reload the original audio: {0}",
        ["Fade.In"] = "Start edge",
        ["Fade.Out"] = "End edge",
        ["Fade.Extend"] = "Extend (use the outside audio at full volume)",
        ["Fade.Hint.In"] = "Fade in: the first N ms of the region ramp up from silence.",
        ["Fade.Hint.In.Extend"] = "Extend: N ms of the audio before the region play at full volume over the end of the previous region (before the first region they are added as a lead-in).",
        ["Fade.Hint.Out"] = "Fade out: N ms of the audio after the region ramp down to silence over the start of the next region (after the last region they are added as a tail).",
        ["Fade.Hint.Out.Extend"] = "Extend: N ms of the audio after the region play at full volume over the start of the next region (after the last region they are added as a tail).",
        ["Fade.Max"] = "0 – {0} ms (limited by the audio available)",
        ["Fade.Region"] = "Region {0}",
        ["Confirm.Title"] = "Check the cut point",
        ["Confirm.Line"] = "{0}: {1} ms ({2}) away from the nearest 1/1·1/2 beat line or BPM change at {3}.",
        ["Confirm.Start"] = "Start",
        ["Confirm.End"] = "End",
        ["Confirm.Cells"] = "1/{0} snap × {1}",
        ["Confirm.Beats"] = "{0} beat(s)",
        ["Confirm.Measures"] = "{0} measure(s)",
        ["Confirm.Question"] = "Is this intended?",
        ["Confirm.Yes"] = "Yes, keep it",
        ["Confirm.No"] = "No, cancel",
        ["Dialog.OK"] = "OK",
        ["Export.Title"] = "Export cut version",
        ["Export.Format"] = "Audio format",
        ["Export.Fmt.Mp3_192"] = "MP3 192 kbps (rankable)",
        ["Export.Fmt.Mp3_320"] = "MP3 320 kbps",
        ["Export.Fmt.Ogg_06"] = "OGG Vorbis q0.6 (~192 kbps)",
        ["Export.Fmt.Ogg_08"] = "OGG Vorbis q0.8",
        ["Export.Fmt.Wav"] = "WAV 16-bit",
        ["Export.Crossfade"] = "De-click crossfade at seams (ms)",
        ["Export.Tail"] = "Silence after the end (ms)",
        ["Export.TitleSuffix"] = "Title suffix",
        ["Export.Version"] = "Difficulty name (empty = keep)",
        ["Export.Creator"] = "Creator",
        ["Export.Content"] = "Beatmap content",
        ["Export.KeepNotes"] = "Keep the notes of this difficulty",
        ["Export.EmptyNotes"] = "Empty difficulty (timing only, map the cut from scratch)",
        ["Export.NoOsu"] = "Audio only (no .osu)",
        ["Export.KeepBookmarks"] = "Keep the bookmarks that fall inside the kept regions",
        ["Export.Scroll"] = "Scroll speed (osu!mania)",
        ["Export.Scroll.Normalize"] = "Normalize: 1.0x at the main BPM {0} (every SV × {1})",
        ["Export.Scroll.NormalizeSame"] = "Normalize: already 1.0x at the main BPM {0} (nothing to change)",
        ["Export.Scroll.Keep"] = "Export as is (SVs unchanged)",
        ["Export.Scroll.Info"] = "osu!mania scrolls relative to the most common BPM. Original {0} → cut {1}; SV in the cut's main-BPM sections: {2}.",
        ["Export.Scroll.Info.NoNotes"] = " (no notes: measured up to the end of the cut audio)",
        ["Export.ScrollDone"] = "Scroll speed normalized: 1.0x at {0} BPM (SV × {1}; {2} green line(s) added, {3} scaled).",
        ["Export.ScrollKept"] = "SVs left unchanged: main BPM {0} → {1}, so the main-BPM sections scroll at {2}x.",
        ["Export.Output"] = "Output folder",
        ["Export.Out.Songs"] = "New folder in osu! Songs",
        ["Export.Out.Same"] = "Same folder as the beatmap",
        ["Export.Out.Custom"] = "Custom folder",
        ["Export.Browse"] = "Browse...",
        ["Export.AudioName"] = "Audio file name",
        ["Export.CopyBg"] = "Copy background image",
        ["Export.Verify"] = "Verify offset with BASS (recommended)",
        ["Export.Run"] = "Export",
        ["Export.Close"] = "Close",
        ["Export.OpenFolder"] = "Open output folder",
        ["Export.Summary"] = "{0} region(s), {1} of audio",
        ["Export.Done"] = "Exported {0} ({1}){2} to {3}",
        ["Export.AndOsu"] = " and {0}",
        ["Export.Offset"] = "Offset check: {0}",
        ["Export.Stats"] = "{0} objects kept, {1} removed, {2} shortened, {3} red line(s) inserted.",
        ["Export.F5"] = "Press F5 in osu! song select to see the new folder.",
        ["Export.Failed"] = "Export failed: {0}",
        ["Export.ChooseFolder"] = "Choose an output folder first.",
        ["Export.Working"] = "Exporting...",
        ["Export.ChooseTitle"] = "Choose the output folder",
        ["Issues.Title"] = "Overlapping notes",
        ["Issues.Heading"] = "The following places contain overlapping notes created by the cut. Continue anyway?",
        ["Issues.Summary"] = "{0} overlapping / duplicated note(s), {1} hold note(s) shortened to less than a quarter beat. They will be written as they are; fix them in the editor afterwards.",
        ["Issues.Show"] = "▸ Show where ({0})",
        ["Issues.Hide"] = "▾ Hide the list",
        ["Issues.Continue"] = "Continue anyway",
        ["Issues.Cancel"] = "Cancel",
        ["Issues.Orig"] = "(original {0})",
        ["Issues.Column"] = "col {0}",
        ["Issue.Overlap"] = "hold note ends on/after the next note ({0} ms overlap)",
        ["Issue.Duplicate"] = "two notes at the same time",
        ["Issue.ShortHold"] = "hold note cut down to {0} ms",
        ["Shortcuts.Title"] = "Keyboard shortcuts",
        ["About.Text"] = "CV!mania {0} by Tamania\n\nCut Version maker for osu!mania (stable): reads the beatmap selected in osu!, lets you pick regions while listening, and exports a cut version whose audio, timing and scroll speed stay as intended.\n\nAudio: BASS 2.4 (un4seen.com, free for non-commercial use), LAME (LGPL), OggVorbisEncoder.\nosu! memory: OsuMemoryDataProvider (GPL-3.0).\nLicense: GPL-3.0",
    };

    private static readonly Dictionary<string, string> Ko = new()
    {
        ["App.Title"] = "CV!mania by Tamania",
        ["Menu.File"] = "파일(_F)",
        ["Menu.Open"] = ".osu 열기(_O)...",
        ["Menu.Reload"] = "비트맵 다시 불러오기(_R)",
        ["Menu.Export"] = "Cut Ver. 내보내기(_E)...",
        ["Menu.Exit"] = "종료(_X)",
        ["Menu.View"] = "보기(_V)",
        ["Menu.ZoomFit"] = "전체 보기",
        ["Menu.FollowPlayhead"] = "재생 중 재생 위치 따라가기",
        ["Menu.FollowOsu"] = "osu!에서 선택한 비트맵 따라가기",
        ["Menu.ShowNotes"] = "파형 아래 노트 표시",
        ["Menu.ShowBookmarks"] = "북마크 표시",
        ["Menu.Language"] = "언어(_L)",
        ["Menu.Help"] = "도움말(_H)",
        ["Menu.Shortcuts"] = "단축키",
        ["Menu.About"] = "CV!mania 정보",
        ["Status.NotRunning"] = "osu! 실행 안 됨",
        ["Status.Reading"] = "osu! 발견 - 메모리 읽는 중...",
        ["Status.Connected"] = "osu! {0} - {1}",
        ["Map.None"] = "불러온 비트맵 없음 - osu!에서 맵을 고르거나 .osu 파일을 여기에 놓으세요",
        ["Map.Info"] = "{0} · {1} · 노트 {2}개 · 빨간 줄 {3}개 · 주 BPM {4} · {5}",
        ["Map.Follow"] = "osu! 선택 따라가기",
        ["Map.Open"] = ".osu 열기...",
        ["Map.Reload"] = "다시 불러오기",
        ["Bpm.Label"] = "BPM 구간:",
        ["Snap.Label"] = "스냅:",
        ["Snap.Measure"] = "마디",
        ["Snap.Off"] = "끄기",
        ["Snap.Tip"] = "선택이 이 격자에 스냅됩니다. 선 색은 osu! 에디터와 같습니다.",
        ["Transport.Play"] = "재생 (Space)",
        ["Transport.Pause"] = "일시정지 (Space)",
        ["Transport.Stop"] = "정지 (Esc)",
        ["Transport.SelStart"] = "선택 시작 = 재생 위치 (I)",
        ["Transport.SelEnd"] = "선택 끝 = 재생 위치 (O)",
        ["Transport.Loop"] = "선택 반복 (L)",
        ["Transport.Follow"] = "재생 위치 따라가기",
        ["Transport.ZoomFit"] = "전체 보기 (Z)",
        ["Transport.Volume"] = "음량",
        ["Transport.Preview"] = "미리듣기: 잘린 결과 재생 중 (P로 원곡 복귀)",
        ["Regions.Title"] = "유지할 구간",
        ["Regions.Col.Start"] = "시작",
        ["Regions.Col.End"] = "끝",
        ["Regions.Col.Length"] = "길이",
        ["Regions.Col.Out"] = "출력 시작",
        ["Regions.Col.FadeIn"] = "시작 처리",
        ["Regions.Col.FadeOut"] = "끝 처리",
        ["Regions.Col.Grid"] = "격자",
        ["Regions.Add"] = "선택 추가·분할 (Enter)",
        ["Regions.Delete"] = "선택 부분·구간 삭제 (Del)",
        ["Regions.Clear"] = "구간 모두 지우기",
        ["Regions.FadeIn"] = "시작 처리...",
        ["Regions.FadeOut"] = "끝 처리...",
        ["Regions.None"] = "구간 없음 (구간 밖은 모두 잘립니다).",
        ["Regions.Summary"] = "구간 {0}개 → {1}",
        ["Selection.Text"] = "선택 {0} - {1} ({2})",
        ["Selection.Inside"] = "구간 {0} 안: Enter = 분할, Delete = 이 부분 삭제",
        ["Selection.Outside"] = "Enter = 구간으로 추가, 우클릭 = 선택 지우기",
        ["Selection.StartOnly"] = "선택 시작 {0} - O로 끝을 정하세요",
        ["Grid.Downbeat"] = "마디 시작",
        ["Grid.OnBeat"] = "박자 위",
        ["Grid.Off"] = "박자에서 {0} ms 벗어남",
        ["Bottom.Preview"] = "미리듣기 (P)",
        ["Bottom.BackToOriginal"] = "원곡으로 (P)",
        ["Bottom.Export"] = "내보내기...",
        ["Msg.AddRegionHint"] = "미리듣기·내보내기를 하려면 구간을 하나 이상 추가하세요.",
        ["Msg.Loaded"] = "{0} 불러옴 ({1} Hz, {2}채널, {3}). 파형을 드래그해 선택하고 Enter로 유지하세요.",
        ["Msg.Decoding"] = "BASS로 오디오 디코딩 중...",
        ["Msg.ReadFail"] = "{0}을(를) 읽을 수 없음: {1}",
        ["Msg.AudioMissing"] = "오디오 파일 '{0}'이(가) 비트맵 옆에 없습니다.",
        ["Msg.DecodeFail"] = "오디오를 디코딩할 수 없음: {0}",
        ["Msg.PlayFail"] = "재생을 시작할 수 없음: {0}",
        ["Msg.Rendering"] = "미리듣기 렌더링 중...",
        ["Msg.PreviewReady"] = "미리듣기 준비: {0}. 구간 안을 클릭하면 이동, P로 원곡 복귀.",
        ["Msg.PreviewFail"] = "미리듣기 실패: {0}",
        ["Msg.ReloadFail"] = "원곡을 다시 불러올 수 없음: {0}",
        ["Fade.In"] = "시작 처리",
        ["Fade.Out"] = "끝 처리",
        ["Fade.Extend"] = "확장 (구간 밖 소리를 그대로 100%로 붙임)",
        ["Fade.Hint.In"] = "페이드 인: 구간의 처음 N ms가 무음에서 점점 커집니다.",
        ["Fade.Hint.In.Extend"] = "확장: 구간 앞의 소리 N ms를 그대로(100%) 앞 구간 끝 위에 겹칩니다. 첫 구간이면 앞에 붙습니다.",
        ["Fade.Hint.Out"] = "페이드 아웃: 구간 뒤의 소리 N ms가 점점 0으로 줄며 다음 구간 시작 위에 겹칩니다. 마지막 구간이면 뒤에 붙습니다.",
        ["Fade.Hint.Out.Extend"] = "확장: 구간 뒤의 소리 N ms를 그대로(100%) 다음 구간 시작 위에 겹칩니다. 마지막 구간이면 뒤에 붙습니다.",
        ["Fade.Max"] = "0 – {0} ms (실제로 있는 소리만큼)",
        ["Fade.Region"] = "구간 {0}",
        ["Confirm.Title"] = "자르는 위치 확인",
        ["Confirm.Line"] = "{0}: 가장 가까운 1/1·1/2 박자선·BPM 변경선({3})에서 {1} ms ({2}) 떨어져 있습니다.",
        ["Confirm.Start"] = "시작",
        ["Confirm.End"] = "끝",
        ["Confirm.Cells"] = "1/{0} 스냅 {1}칸",
        ["Confirm.Beats"] = "{0}박",
        ["Confirm.Measures"] = "{0}마디",
        ["Confirm.Question"] = "의도한 것인가요?",
        ["Confirm.Yes"] = "예, 그대로",
        ["Confirm.No"] = "아니요, 취소",
        ["Dialog.OK"] = "확인",
        ["Export.Title"] = "Cut Ver. 내보내기",
        ["Export.Format"] = "오디오 형식",
        ["Export.Fmt.Mp3_192"] = "MP3 192 kbps (랭크 가능)",
        ["Export.Fmt.Mp3_320"] = "MP3 320 kbps",
        ["Export.Fmt.Ogg_06"] = "OGG Vorbis q0.6 (약 192 kbps)",
        ["Export.Fmt.Ogg_08"] = "OGG Vorbis q0.8",
        ["Export.Fmt.Wav"] = "WAV 16비트",
        ["Export.Crossfade"] = "이음새 크로스페이드 (ms)",
        ["Export.Tail"] = "끝 뒤 무음 (ms)",
        ["Export.TitleSuffix"] = "제목 접미사",
        ["Export.Version"] = "난이도 이름 (비우면 유지)",
        ["Export.Creator"] = "제작자",
        ["Export.Content"] = "채보 내용",
        ["Export.KeepNotes"] = "이 난이도의 노트 유지",
        ["Export.EmptyNotes"] = "빈 난이도 (타이밍만, 새로 찍기용)",
        ["Export.NoOsu"] = "오디오만 (.osu 없음)",
        ["Export.KeepBookmarks"] = "기존 북마크 유지 (유지 구간 안에 있는 북마크만 남음)",
        ["Export.Scroll"] = "스크롤 속도 (osu!mania)",
        ["Export.Scroll.Normalize"] = "변속 없이 유지: 주 BPM {0}에서 1x가 되도록 SV 정규화 (모든 SV × {1})",
        ["Export.Scroll.NormalizeSame"] = "변속 없이 유지: 주 BPM {0}에서 이미 1x (변경 없음)",
        ["Export.Scroll.Keep"] = "그대로 내보내기 (SV 변경 없음)",
        ["Export.Scroll.Info"] = "osu!mania는 주 BPM(가장 오래 쓰인 BPM)을 기준으로 스크롤합니다. 원본 {0} → 컷 {1}; 컷의 주 BPM 구간 SV: {2}.",
        ["Export.Scroll.Info.NoNotes"] = " (노트 없음: 컷 오디오 끝까지 기준)",
        ["Export.ScrollDone"] = "스크롤 속도 정규화: {0} BPM에서 1x (SV × {1}; 초록 줄 {2}개 추가, {3}개 조정).",
        ["Export.ScrollKept"] = "SV 그대로: 주 BPM {0} → {1}, 주 BPM 구간이 {2}x로 스크롤됩니다.",
        ["Export.Output"] = "출력 폴더",
        ["Export.Out.Songs"] = "osu! Songs에 새 폴더",
        ["Export.Out.Same"] = "비트맵과 같은 폴더",
        ["Export.Out.Custom"] = "직접 선택",
        ["Export.Browse"] = "찾아보기...",
        ["Export.AudioName"] = "오디오 파일 이름",
        ["Export.CopyBg"] = "배경 이미지 복사",
        ["Export.Verify"] = "BASS로 오프셋 검증 (권장)",
        ["Export.Run"] = "내보내기",
        ["Export.Close"] = "닫기",
        ["Export.OpenFolder"] = "출력 폴더 열기",
        ["Export.Summary"] = "구간 {0}개, 오디오 {1}",
        ["Export.Done"] = "{0} ({1}){2} 내보냄 → {3}",
        ["Export.AndOsu"] = " 및 {0}",
        ["Export.Offset"] = "오프셋 검증: {0}",
        ["Export.Stats"] = "노트 {0}개 유지, {1}개 제거, {2}개 단축, 빨간 줄 {3}개 삽입.",
        ["Export.F5"] = "osu! 곡 선택 화면에서 F5를 누르면 새 폴더가 보입니다.",
        ["Export.Failed"] = "내보내기 실패: {0}",
        ["Export.ChooseFolder"] = "먼저 출력 폴더를 선택하세요.",
        ["Export.Working"] = "내보내는 중...",
        ["Export.ChooseTitle"] = "출력 폴더 선택",
        ["Issues.Title"] = "겹치는 노트 확인",
        ["Issues.Heading"] = "다음과 같은 구간에 겹치는 노트가 존재합니다. 계속 진행하시겠습니까?",
        ["Issues.Summary"] = "겹치거나 중복된 노트 {0}개, 1/4박보다 짧아진 롱노트 {1}개. 그대로 저장되니 이후 에디터에서 손보세요.",
        ["Issues.Show"] = "▸ 위치 보기 ({0}개)",
        ["Issues.Hide"] = "▾ 목록 접기",
        ["Issues.Continue"] = "계속 진행",
        ["Issues.Cancel"] = "취소",
        ["Issues.Orig"] = "(원곡 {0})",
        ["Issues.Column"] = "{0}열",
        ["Issue.Overlap"] = "롱노트 끝이 다음 노트와 겹침 ({0} ms)",
        ["Issue.Duplicate"] = "같은 시각에 노트 2개",
        ["Issue.ShortHold"] = "롱노트가 {0} ms로 잘림",
        ["Shortcuts.Title"] = "단축키",
        ["About.Text"] = "CV!mania {0} by Tamania\n\nosu!mania (stable) Cut Ver. 제작기: osu!에서 선택한 비트맵을 읽어 들으면서 구간을 고르고, 오디오·타이밍·스크롤 속도가 의도대로 유지되는 Cut Ver.를 내보냅니다.\n\n오디오: BASS 2.4 (un4seen.com, 비상업 무료), LAME (LGPL), OggVorbisEncoder.\nosu! 메모리: OsuMemoryDataProvider (GPL-3.0).\n라이선스: GPL-3.0",
    };
}
